name: "Build usd from gltf"
on: [push, pull_request]
jobs:
  build-win-10:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ilammy/setup-nasm@v1
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: Install USD
        run: |
          git clone -b release https://github.com/PixarAnimationStudios/USD.git
        shell: bash        
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Install Python deps
        run: |
          pip install PyOpenGL PySide2

      - name: Install boost
        uses: MarkusJx/install-boost@v1.0.1
        id: install-boost
        with:
          # REQUIRED: Specify the required boost version
          # A list of supported versions can be found here: 
          # https://github.com/actions/boost-versions/blob/main/versions-manifest.json
          boost_version: 1.73.0
      - name: Install usd
        run: |
          python USD/build_scripts/build_usd.py "USD-build"
        shell: cmd
      - name: Install cmake
        run: |
          mkdir build
          cd build
          cmake -GNinja ..
        shell: bash
      
      - name: ninja
        run: |
          ninja
        shell: bash

      - name: pillow
        run: |
          pip install Pillow
        shell: bash

      - uses: actions/upload-artifact@v2
        with:
          name: usd_from_gltf
          path: build/usd_from_gltf.exe