name: "Build usd from gltf"
on: [push, pull_request]
jobs:
  build-win-10:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install cmake
        run: |
          mkdir build
          cmake -GNinja ..
        shell: bash

      - name: ninja
        run: |
          ninja
        shell: bash

      - uses: actions/upload-artifact@v2
        with:
          name: usd_from_gltf
          path: build/usd_from_gltf.exe